Add spiffe-csi driver support
philips-labs/helm-charts pull request #60
Opened 2022-10-24 17:57 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>

/cc @dentrax

PTAL @marcofranssen 

You can test it with the following steps:

1. Deploy the example _client_ pod with the following manifest:

```yaml
cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: client
          image: gcr.io/spiffe-io/spire-agent:1.4.4
          command: ["sleep"]
          args: ["1000000000"]
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
EOF
```

2. Now, you can shell into the _client_ pod and test it by fetching the SVID for it:

```shell
$ /opt/spire/bin/spire-agent api fetch -socketPath /spiffe-workload-api/agent.sock
Received 1 svid after 13.278918ms

SPIFFE ID:		spiffe://example.org/ns/default/sa/default
SVID Valid After:	2022-10-24 17:51:57 +0000 UTC
SVID Valid Until:	2022-10-24 18:52:07 +0000 UTC
CA #1 Valid After:	2022-10-24 17:50:42 +0000 UTC
CA #1 Valid Until:	2022-10-25 17:50:52 +0000 UTC
```

2022-10-25 07:53 UTC, marcofranssen requested changes
Thanks a lot for this contribution. 🎉 

I'll give this a test as soon as possible. For now a few nit picky suggestions.

2022-10-25 07:53 UTC, marcofranssen commented on charts/spire/templates/agent-daemonset.yaml
> +            type: Directory
Please end this file with a new line.

2022-10-25 07:53 UTC, marcofranssen commented on charts/spire/values.yaml
> +    tag: "1.4.4"
I prefer to bump the appVersion in Chart.yaml and leave this empty.

2022-10-25 07:53 UTC, marcofranssen commented on charts/spire/values.yaml
> +    tag: "1.4.4"
I prefer to bump the appVersion in Chart.yaml and leave this empty.

2022-10-25 07:53 UTC, marcofranssen commented on charts/spire/values.yaml
> +    tag: "1.4.4"
I prefer to bump the appVersion in Chart.yaml and leave this empty.

2022-10-25 07:53 UTC, marcofranssen commented on charts/spire/values.yaml
> +    tag: "1.4.4"
I prefer to bump the appVersion in Chart.yaml and leave this empty.

2022-10-25 13:14 UTC, marcofranssen commented on charts/spire-client-example/README.md
> -<!-- This README.md is generated. -->
Please us the template in the command.

https://github.com/philips-labs/helm-charts/blob/main/.github/README.md.tmpl

```shell
helm-docs -g charts/spire -t .github/README.md.tmpl
```

I should probably document this in a CONTRIBUTING.md

2022-10-31 07:49 UTC, developer-guy commented
hello @marcofranssen, I just wanted to let you know that similar work has been done in the FRSCA project, I'm linking that issue.

> _https://github.com/buildsec/frsca/pull/355_

2022-10-31 08:15 UTC, marcofranssen approved these changes
LGTM

2022-10-31 08:15 UTC, merged

2022-10-31 09:46 UTC, developer-guy commented on charts/spire/templates/agent-daemonset.yaml
> +        - name: spiffe-csi-driver
yeah, I'll do it in separate PR

2022-10-31 09:46 UTC, developer-guy commented on charts/spire/templates/agent-daemonset.yaml
> +          image: quay.io/k8scsi/csi-node-driver-registrar:v2.0.1
yeah, I'll do it in separate PR